### ISSUE TITLE
HomePage is rendering twice

### ISSUE THREAD

**Issue by destroyeraseimprove** [RichardBray/no-redux#4]
Hello.
Thanks for the really great article. It’s very good understandable.
I have a question.
I can see that HomePage component is rendering twice.
I put console.log(‘rendered’) inside of HomePage and I can see it two times.
Is it possible to avoid that?

**Comment by RichardBray** [comment]
Hey there super sorry for the late reply. I don't think you need to worry about the page loading twice, I have a feeling it loads the page once without data then loads it again, but I could be wrong.

**Comment by destroyeraseimprove** [comment]
Thank you so much for you reply. I already figured out the concept. I
shouldn't care about re-rendering because only modified elements are
being affected. One more time thank you for the wonderful article!

Alex.

пт, 8 мая 2020 г. в 18:50, Richard Oliver Bray <notifications@github.com>:

**Comment by RichardBray** [comment]
You're very welcome. If it's okay with you I'm going to close this issue.
